baseURL = "https://cch0124.github.io/"
languageCode = "en-us"
googleAnalytics = "UA-127407214-1"
theme = ["aafu"]

[params]
    title = "Kevin Blog"
    author = "Kevin Chen"
    description = "Kevin learning"
    copyright = "short copyright message"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "pinkish"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Kevin Chen"
        tagline = "IT Blog"
        location = "Taiwan"
        photo = "cch.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/kevinchen0124"
            title = "LinkedIn"		
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/CCH0124"
            title = "GitHub"
    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "時間帶走記憶，我將一切變成回憶。有觸及的領域 Linux、Network、容器、JAVA 等。因為發展得太恐怖了，我只能一直保持學習的心。"

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "RD 工程師"
            dates = "2021/1 - *Present*"
            company = ""
            details = "以 Spring boot 為主進行 API 開發"
#        [[params.experience.list]]
#            position = "Job Title"
#            dates = "2018 - 2019"
#            url = "#"
#            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "電子工程碩士學位"
            college = "National Kaohsiung University of Science and Technology"
            dates = "2018 - 2020"
            thesis_title = "植基於深度學習與高斯混合模型之DDoS未知攻擊偵測"
            thesis_url = "https://hdl.handle.net/11296/a5waw2"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        #format = ["date", "authors", "title", "journal"]
        format = ["date", "authors", "title"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings", "IT 鐵人賽"]
        [[params.publication.list]]
            title = "Kubernetes Learning"
            date = "2020"
            authors = "Kevin Chen"
            url = "https://ithelp.ithome.com.tw/users/20104688/ironman/3727"
            type = "IT 鐵人賽"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
#            title = "Project 1"
#            url = "#"
#            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Java"
            skillrating = 70
        [[params.skill.list]]
            skill = "Spring boot"
            skillrating = 70
        [[params.skill.list]]
            skill = "git"
            skillrating = 70
        [[params.skill.list]]
            skill = "docker"
            skillrating = 90
        [[params.skill.list]]
            skill = "ubuntu"
            skillrating = 80

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Camping"
        [[params.hobby.list]]
            hobby = "Baseball"
        [[params.hobby.list]]
            hobby = "Astronomical"
